USB_VID = 0x303A
USB_PID = 0x80B1
USB_PRODUCT = "RoboCloud"
USB_MANUFACTURER = "Project Stida"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

# The default queue depth of 16 overflows on release builds,
# so increase it to 32.
CFLAGS += -DCFG_TUD_TASK_QUEUE_SZ=32

CIRCUITPY_ESP_FLASH_MODE=dio
CIRCUITPY_ESP_FLASH_FREQ=40m
CIRCUITPY_ESP_FLASH_SIZE=4MB

FROZEN_MPY_DIRS += $(TOP)/frozen/CircuitPython_RoboCloudLib

CIRCUITPY_MODULE=wrover
